// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCRQm8QcnIb9cXblbHv09mhQSB_nTRriXY',
    appId: '1:835002877452:web:e66bdc72fad75b207e1029',
    messagingSenderId: '835002877452',
    projectId: 'respawn-d7753',
    authDomain: 'respawn-d7753.firebaseapp.com',
    storageBucket: 'respawn-d7753.firebasestorage.app',
    measurementId: 'G-LP9NPNET1Q',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAvqZWth2KL4oSz3HfGrA3iLKV59dcC6h8',
    appId: '1:835002877452:android:0a3e5eda18cd607b7e1029',
    messagingSenderId: '835002877452',
    projectId: 'respawn-d7753',
    storageBucket: 'respawn-d7753.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC_krcLcl7D722XjhOonO7qSv82CTKB86c',
    appId: '1:835002877452:ios:64553fe560a1c8537e1029',
    messagingSenderId: '835002877452',
    projectId: 'respawn-d7753',
    storageBucket: 'respawn-d7753.firebasestorage.app',
    iosBundleId: 'com.example.projectrespawn',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC_krcLcl7D722XjhOonO7qSv82CTKB86c',
    appId: '1:835002877452:ios:64553fe560a1c8537e1029',
    messagingSenderId: '835002877452',
    projectId: 'respawn-d7753',
    storageBucket: 'respawn-d7753.firebasestorage.app',
    iosBundleId: 'com.example.projectrespawn',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCRQm8QcnIb9cXblbHv09mhQSB_nTRriXY',
    appId: '1:835002877452:web:5b64bbe4d5d01c4a7e1029',
    messagingSenderId: '835002877452',
    projectId: 'respawn-d7753',
    authDomain: 'respawn-d7753.firebaseapp.com',
    storageBucket: 'respawn-d7753.firebasestorage.app',
    measurementId: 'G-46YZ2WCFG1',
  );

}